### ISSUE TITLE
React Native 0.68 Android Build Error

### ISSUE THREAD

**Issue by saamerm** [miyabi/react-native-passkit-wallet#20]
Getting the following error when ever I run `npm run android` in the terminal, anyone have any recommendations?:
```
> Configure project :app
Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.
Reading env from: .env

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
6 actionable tasks: 6 up-to-date

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/saamer/Documents/GitHub/GSC-RN/gsc-mobile/node_modules/react-native-passkit-wallet/android/build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':react-native-passkit-wallet'.
> Could not find method provided() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/saamer/Documents/GitHub/GSC-RN/gsc-mobile/node_modules/react-native-passkit-wallet/android/build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':react-native-passkit-wallet'.
> Could not find method provided() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

    at makeError (/Users/saamer/Documents/GitHub/GSC-RN/gsc-mobile/node_modules/execa/index.js:174:9)
    at /Users/saamer/Documents/GitHub/GSC-RN/gsc-mobile/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/saamer/Documents/GitHub/GSC-RN/gsc-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/saamer/Documents/GitHub/GSC-RN/gsc-mobile/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
```

**Comment by meoner** [comment]
Same issue. Dou you have any solution?

**Comment by saamerm** [comment]
@meoner Salam and Eid Mubarak! We fixed it by switching to `react-native-wallet-passes` v1.2.2. It was effortless and smooth, just needed to change two words
